version: "3.3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "1234"
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
    ports:
    - 8080:8080
    - 5005:8787
    volumes:
    - ./target/libs/emailValidator-1.1.jar:/opt/jboss/keycloak/standalone/deployments/emailValidator-1.1.jar

